In [70]:
import pandas as pd
import numpy as np
import glob
import os
path = r"C:\Users\Administrator\Dropbox\Metabolism"

In [71]:
clinical_information = pd.read_csv(r"C:\Users\Administrator\Dropbox\Metabolism\clinical information.csv", encoding='utf-8')
miR = pd.read_csv(r"C:\Users\Administrator\Dropbox\Metabolism\miR.csv", encoding='utf-8')
mRNA = pd.read_csv(r"C:\Users\Administrator\Dropbox\Metabolism\mRNA.csv", encoding='utf-8')
output_file = (r"C:\Users\Administrator\Dropbox\Metabolism\results.csv")

In [72]:
df_merged_mRNA = pd.merge(mRNA, clinical_information, on="ID", how="inner")

In [73]:
df_merged_mRNA

ID    ABAT  ABCC6P2  ACSM5  ANGPTL4     ANXA1     AQP4      AXL  \
0      BC1   58.09   460.40  34.42    64.54   3622.94   922.95  1131.63   
1     BC10   15.94   119.15   3.36    51.19   1837.64   139.29   139.29   
2    BC103   42.49   102.76  10.87    60.27   2143.06   342.85   342.85   
3    BC106  638.79  3311.23  21.00    75.26   5997.66  1121.83  1121.83   
4    BC107  152.55  1422.69  36.48    59.69  12717.99  1489.02  1489.02   
..     ...     ...      ...    ...      ...       ...      ...      ...   
287    NaN     NaN      NaN    NaN      NaN       NaN      NaN      NaN   
288    NaN     NaN      NaN    NaN      NaN       NaN      NaN      NaN   
289    NaN     NaN      NaN    NaN      NaN       NaN      NaN      NaN   
290    NaN     NaN      NaN    NaN      NaN       NaN      NaN      NaN   
291    NaN     NaN      NaN    NaN      NaN       NaN      NaN      NaN   

        BEX4     CBX5  ...  histology  \
0     522.79   733.62  ...        1.0   
1     192.99   256.77  ...        1.0   
2     297.40   342.85  ...        1.0   
3    1100.83  1211.08  ...        1.0   
4     994.89  1435.96  ...        1.0   
..       ...      ...  ...        ...   
287      NaN      NaN  ...        NaN   
288      NaN      NaN  ...        NaN   
289      NaN      NaN  ...        NaN   
290      NaN      NaN  ...        NaN   
291      NaN      NaN  ...        NaN   

     stage\n\n11-Ia\n12-Ib\n20-II               \n21-IIa \n22-IIb\n30-III                  \n31-IIIa \n32-IIIb\n40-IV  \
0                                                 11.0                                                                  
1                                                 31.0                                                                  
2                                                 11.0                                                                  
3                                                 11.0                                                                  
4                                                 11.0                                                                  
..                                                 ...                                                                  
287                                                NaN                                                                  
288                                                NaN                                                                  
289                                                NaN                                                                  
290                                                NaN                                                                  
291                                                NaN                                                                  

     status_recurrence  date_recurrence  \
0                  0.0              NaN   
1                  0.0              NaN   
2                  0.0              NaN   
3                  0.0              NaN   
4                  0.0              NaN   
..                 ...              ...   
287                NaN              NaN   
288                NaN              NaN   
289                NaN              NaN   
290                NaN              NaN   
291                NaN              NaN   

     FU status\n\n0=alive without ds                     \n1=alive with recurren ds,                                  \n2=dead without ds                                   \n3=dead d/t recurrent ds                        \n4=dead, unknown                            \n5= FU loss  \
0                                                  0.0                                                                                                                                                                                                                                   
1                                                  0.0                          

In [74]:
df_merged_mRNA = df_merged_mRNA.rename(columns={"'stage\n\n11-Ia\n12-Ib\n20-II               \n21-IIa \n22-IIb\n30-III                  \n31-IIIa \n32-IIIb\n40-IV":"stage"}, inplace=True)

In [80]:
df_describe.to_csv("describe_mRNA.csv", mode="w")

NameError: name 'df_describe' is not defined

In [93]:
df_merged_mRNA.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            282, 283, 284, 285, 286, 287, 288, 289, 290, 291],
           dtype='int64', length=292)

In [79]:
df_merged_mRNA.columns[0:100]

AttributeError: 'NoneType' object has no attribute 'columns'

In [86]:
np.corrcoef(df_merged_mRNA["ABCC6P2"], df_merged_mRNA["PFKP"])

array([[nan, nan],
       [nan, nan]])

In [91]:
np.corrcoef(df_merged_mRNA["ABCC6P2"].dropna(), df_merged_mRNA["OS time"].dropna())

array([[ 1.        , -0.01889356],
       [-0.01889356,  1.        ]])

In [92]:
np.corrcoef(df_merged_mRNA["ABAT"].dropna(), df_merged_mRNA["OS time"].dropna())

array([[ 1.        , -0.08632549],
       [-0.08632549,  1.        ]])

In [96]:
np.corrcoef(df_merged_mRNA["ACSM5"].dropna(), df_merged_mRNA["OS time"].dropna())

array([[1.        , 0.01887212],
       [0.01887212, 1.        ]])

In [97]:
np.corrcoef(df_merged_mRNA["ANGPTL4"].dropna(), df_merged_mRNA["OS time"].dropna())

array([[ 1.        , -0.05731205],
       [-0.05731205,  1.        ]])

In [111]:
for g in df_merged_mRNA.columns:
    np.corrcoef(df_merged_mRNA[g].dropna(), df_merged_mRNA["OS time"].dropna())

TypeError: unsupported operand type(s) for /: 'str' and 'int'

clmn

In [125]:
all(isinstance(x,str) for x in clmn)

True

In [134]:
clmn=list(df_merged_mRNA.iloc[:,1:-16])
for i in clmn: 
    print(i)
    print(np.corrcoef(df_merged_mRNA[i].dropna(), df_merged_mRNA["OS time"].dropna()))

ABAT
[[ 1.         -0.08632549]
 [-0.08632549  1.        ]]
ABCC6P2
[[ 1.         -0.01889356]
 [-0.01889356  1.        ]]
ACSM5
[[1.         0.01887212]
 [0.01887212 1.        ]]
ANGPTL4
[[ 1.         -0.05731205]
 [-0.05731205  1.        ]]
ANXA1
[[1.         0.03874173]
 [0.03874173 1.        ]]
AQP4
[[1.         0.05504605]
 [0.05504605 1.        ]]
AXL
[[1.        0.0560972]
 [0.0560972 1.       ]]
BEX4
[[1.         0.11017867]
 [0.11017867 1.        ]]
CBX5
[[1.         0.05555733]
 [0.05555733 1.        ]]
CCNB1
[[ 1.         -0.22161366]
 [-0.22161366  1.        ]]
CD109
[[ 1.         -0.13194518]
 [-0.13194518  1.        ]]
CD274
[[ 1.         -0.00245287]
 [-0.00245287  1.        ]]
CECR1
[[1.         0.19749634]
 [0.19749634 1.        ]]
CLIC6
[[ 1.         -0.06439435]
 [-0.06439435  1.        ]]
CNTN3
[[1.         0.16728189]
 [0.16728189 1.        ]]
CYP4B1
[[1.         0.14389761]
 [0.14389761 1.        ]]
DEPDC1
[[ 1.         -0.11587054]
 [-0.11587054  1.        ]]
DKK

In [135]:
corr = open('corr.txt','a')

In [136]:
clmn=list(df_merged_mRNA.iloc[:,1:-16])
for i in clmn: 
    print(i)
    print(np.corrcoef(df_merged_mRNA[i].dropna(), df_merged_mRNA["RFS time"].dropna()))

ABAT
[[ 1.         -0.03686075]
 [-0.03686075  1.        ]]
ABCC6P2
[[1.00000000e+00 9.68979271e-04]
 [9.68979271e-04 1.00000000e+00]]
ACSM5
[[1.         0.05046236]
 [0.05046236 1.        ]]
ANGPTL4
[[ 1.         -0.07913701]
 [-0.07913701  1.        ]]
ANXA1
[[1.         0.08432959]
 [0.08432959 1.        ]]
AQP4
[[1.         0.08164728]
 [0.08164728 1.        ]]
AXL
[[1.         0.08278233]
 [0.08278233 1.        ]]
BEX4
[[1.         0.10569909]
 [0.10569909 1.        ]]
CBX5
[[1.         0.06981145]
 [0.06981145 1.        ]]
CCNB1
[[ 1.         -0.17910281]
 [-0.17910281  1.        ]]
CD109
[[ 1.         -0.07220944]
 [-0.07220944  1.        ]]
CD274
[[1.         0.02352734]
 [0.02352734 1.        ]]
CECR1
[[1.         0.19524435]
 [0.19524435 1.        ]]
CLIC6
[[ 1.         -0.08232189]
 [-0.08232189  1.        ]]
CNTN3
[[1.         0.16358579]
 [0.16358579 1.        ]]
CYP4B1
[[1.         0.12983529]
 [0.12983529 1.        ]]
DEPDC1
[[ 1.         -0.09034857]
 [-0.09034857  1.  

In [137]:
df_merged_mRNA.isnull().sum() # 모두가 100개의 missing 임 

ID                                 100
ABAT                               100
ABCC6P2                            100
ACSM5                              100
ANGPTL4                            100
                                  ... 
date of death or last follow up    100
OS                                 100
OS time                            100
RFS                                100
RFS time                           100
Length: 72, dtype: int64

In [5]:
df_merged_mRNA.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 292 entries, 0 to 291
Data columns (total 72 columns):
 #   Column                                                                                                                                                                                                                                                                      Non-Null Count  Dtype  
---  ------                                                                                                                                                                                                                                                                      --------------  -----  
 0   ID                                                                                                                                                                                                                                                                          192 non-null    object 
 1  

In [21]:
df_merged_mRNA["ABAT"] = df_merged_mRNA["ABAT"].astype(float)
df_merged_mRNA["age"] = df_merged_mRNA["age"].astype(float)

In [23]:
df_merged_mRNA.columns

Index(['ID', 'ABAT', 'ABCC6P2', 'ACSM5', 'ANGPTL4', 'ANXA1', 'AQP4', 'AXL',
       'BEX4', 'CBX5', 'CCNB1', 'CD109', 'CD274', 'CECR1', 'CLIC6', 'CNTN3',
       'CYP4B1', 'DEPDC1', 'DKK1', 'DNAJC28', 'FABP4', 'FBXO16', 'GFPT2',
       'GGT6', 'GNG7', 'GNMT', 'GPC6', 'IFNG', 'IRX5', 'LDLRAD3', 'LYPD3',
       'MAP1LC3B', 'MERTK', 'MTL5', 'NCKAP5', 'P2RY13', 'PDE6B', 'PFKP',
       'POLR2H', 'PPM1M', 'PTPRH', 'RAB27B', 'RPL13AP17', 'RPS6KL1', 'SFTA3',
       'SFTPC', 'SLC16A1', 'SLC2A1', 'SNN', 'TLE1', 'TM4SF1', 'TOP2A',
       'TRIM27', 'GAPDH', 'HPRT1', 'TBP', 'pathology number', 'hospital ID',
       'birth date', 'sex ', 'age', 'date_operation', 'histology',
       'stage\n\n11-Ia\n12-Ib\n20-II               \n21-IIa \n22-IIb\n30-III                  \n31-IIIa \n32-IIIb\n40-IV',
       'status_recurrence', 'date_recurrence',
       'FU status\n\n0=alive without ds                     \n1=alive with recurren ds,                                  \n2=dead without ds                      

In [31]:
df_merged_mRNA.rename(columns={"stage\n\n11-Ia\n12-Ib\n20-II               \n21-IIa \n22-IIb\n30-III                  \n31-IIIa \n32-IIIb\n40-I":"stage"}, inplace = True)

In [147]:
missing_df = df_merged_mRNA.isnull().sum().reset_index

In [149]:
print(missing_df)

<bound method Series.reset_index of ID                                 100
ABAT                               100
ABCC6P2                            100
ACSM5                              100
ANGPTL4                            100
                                  ... 
date of death or last follow up    100
OS                                 100
OS time                            100
RFS                                100
RFS time                           100
Length: 72, dtype: int64>


In [148]:
missing_df.columns = ["column","count"]

AttributeError: 'method' object has no attribute 'columns'

In [ ]:
missing_df.columns = ["column","count"]
missing_df["ratio"] = missing_df["count"]/df_merged_mRNA.shape[0]
mssing_df.loc[missing_df["ratio"]!=0]

In [142]:
df_merged_mRNA.shape[0]

292

In [143]:
df_merged_mRNA.shape[1]

72

In [16]:
df_merged_mRNA.groupby('stage').median()

KeyError: 'stage'